name: ci
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
      - name: Run tests (files extension)
        run: fluentci run --wasm deno test
        working-directory: ./files
